/*
 * This file was automatically generated by EvoSuite
 * Tue Oct 09 16:17:06 GMT 2018
 */

package testselector.project;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.testdata.EvoSuiteFile;
import org.evosuite.runtime.testdata.FileSystemHandling;
import org.junit.Test;
import org.junit.runner.RunWith;

import static org.evosuite.runtime.EvoAssertions.verifyException;
import static org.junit.Assert.fail;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true)
public class Project_ESTest extends Project_ESTest_scaffolding {

    @Test(timeout = 4000)
    public void test0() throws Throwable {
        FileSystemHandling.shouldAllThrowIOExceptions();
        String[] stringArray0 = new String[0];
        Project project0 = null;
        try {
            project0 = new Project(stringArray0);
            fail("Expecting exception: RuntimeException");

        } catch (RuntimeException e) {
            //
            // Couldn't resolve classpath entry C:\\Users\\Dario\\.m2\\repository\\org\\hamcrest\\hamcrest-all\\1.3\\hamcrest-all-1.3.jar: java.io.IOException: Simulated IOException
            //
            verifyException("soot.SourceLocator", e);
        }
    }

    @Test(timeout = 4000)
    public void test1() throws Throwable {
        EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("java\\lang\\Throwable.class");
        FileSystemHandling.appendStringToFile(evoSuiteFile0, "Jj1f`'R0et$'D;Y@");
        String[] stringArray0 = new String[1];
        stringArray0[0] = "";
        Project project0 = null;
        try {
            project0 = new Project(stringArray0);
            fail("Expecting exception: IllegalArgumentException");

        } catch (IllegalArgumentException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("org.objectweb.asm.ClassReader", e);
        }
    }

    @Test(timeout = 4000)
    public void test2() throws Throwable {
        String[] stringArray0 = new String[2];
        stringArray0[0] = "";
        EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("java\\lang\\Throwable.class");
        byte[] byteArray0 = new byte[2];
        FileSystemHandling.appendDataToFile(evoSuiteFile0, byteArray0);
        stringArray0[1] = "";
        Project project0 = null;
        try {
            project0 = new Project(stringArray0);
            fail("Expecting exception: ArrayIndexOutOfBoundsException");

        } catch (ArrayIndexOutOfBoundsException e) {
            //
            // 6
            //
            verifyException("org.objectweb.asm.ClassReader", e);
        }
    }

    @Test(timeout = 4000)
    public void test3() throws Throwable {
        String[] stringArray0 = new String[1];
        stringArray0[0] = "Q)}";
        Project project0 = null;
        try {
            project0 = new Project(stringArray0);
            fail("Expecting exception: NotDirectoryException");

        } catch (Throwable e) {
            //
            // C:\\Users\\Dario\\IdeaProjects\\soot test context sensitive call graph\\Q)}
            //
            verifyException("testselector.project.Project", e);
        }
    }

    @Test(timeout = 4000)
    public void test4() throws Throwable {
        String[] stringArray0 = new String[1];
        stringArray0[0] = "";
        Project project0 = null;
        try {
            project0 = new Project(stringArray0);
            fail("Expecting exception: RuntimeException");

        } catch (RuntimeException e) {
            //
            // java.util.concurrent.ExecutionException: org.evosuite.runtime.mock.java.lang.MockThrowable: Error: The path 'C:\\Users\\Dario\\.m2\\repository\\org\\hamcrest\\hamcrest-all\\1.3\\hamcrest-all-1.3.jar' does not exist.
            //
            verifyException("soot.SourceLocator", e);
        }
    }

    @Test(timeout = 4000)
    public void test5() throws Throwable {
        String[] stringArray0 = new String[1];
        Project project0 = null;
        try {
            project0 = new Project(stringArray0);
            fail("Expecting exception: NullPointerException");

        } catch (NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("java.io.File", e);
        }
    }
}
